# MJMLTools package init
# Exposes MJMLTag, TagAttrDict, and all tag functions

from ._core import MJMLTag, TagAttrDict
from .tags import (
    mjml,
    head,
    body,
    mj_attributes,
    mj_all,
    mj_class,
    breakpoint,
    font,
    html_attributes,
    html_attribute,
    preview,
    style,
    title,
    accordion,
    accordion_element,
    button,
    carousel,
    carousel_image,
    column,
    divider,
    group,
    hero,
    image,
    navbar,
    raw,
    section,
    social,
    spacer,
    table,
    text,
    wrapper,
    accordion_text,
    accordion_title,
    navbar_link,
    social_element,
)
# _process_mjml_images is called internally by mjml_to_intermediate_email

__all__ = (
    "MJMLTag",
    "TagAttrDict",
    "mjml",
    "head",
    "body",
    "mj_attributes",
    "mj_all",
    "mj_class",
    "breakpoint",
    "font",
    "html_attributes",
    "html_attribute",
    "preview",
    "style",
    "title",
    "accordion",
    "accordion_element",
    "button",
    "carousel",
    "carousel_image",
    "column",
    "divider",
    "group",
    "hero",
    "image",
    "navbar",
    "raw",
    "section",
    "social",
    "spacer",
    "table",
    "text",
    "wrapper",
    "accordion_text",
    "accordion_title",
    "navbar_link",
    "social_element",
)
