project:
  type: website

website:
  title: "Email for Data Science"
  site-url: https://posit-dev.github.io/email-for-data-science/
  navbar:
    left:
      - text: User Guide
        file: index.qmd
      - text: Reference
        file: reference/index.qmd
  sidebar:
    - title: User Guide
      contents:
        - index.qmd
        - summary.qmd
        - section: Content
          contents: 
            - content-embedding.qmd
            - content-layout.qmd
        - section: Configuring
          contents:
            - configuring-subject.qmd
            - configuring-attachments.qmd
        - section: Orchestrating
          contents:
            - orchestrating-auth.qmd
            - orchestrating-tests.qmd

quartodoc:
  package: emailer_lib
  dir: reference
  title: API Reference
  css: reference/_styles-quartodoc.css
  renderer:
    style: markdown
    table_style: description-list

  sections:
    - title: The Email Object
      desc: >
        An email object that in a serializable, previewable format,
        optimized for emails with content generated by data scientists.
      contents:
        - name: IntermediateEmail
          children: linked
        - name: IntermediateEmail.write_preview_email
        - name: IntermediateEmail.write_email_message
        - name: IntermediateEmail.preview_send_email
    - title: Uploading emails
      desc: >
        Converting emails to IntermediateEmails,
        at which point they can be previewed, tested, and sent.
      contents:
        - quarto_json_to_intermediate_email
        - mjml_to_intermediate_email
        - redmail_to_intermediate_email
        - yagmail_to_intermediate_email

    - title: Sending
      desc: >
        Functions to sending emails with different providers.
        And a special handy one to bypass the intermediate object if you are sending a quarto email.
      contents:
        - send_intermediate_email_with_gmail
        - send_intermediate_email_with_smtp
        - send_intermediate_email_with_redmail
        - send_intermediate_email_with_yagmail
        - send_intermediate_email_with_mailgun
        - send_quarto_email_with_gmail


    - title: Utilities
      desc: >
        Previews and more 
      contents:
        - write_email_message_to_file


format:
  html:
    theme:
      - cosmo
      - brand
    css:
      - reference/_styles-quartodoc.css
      - reference/styles.css


