project:
  type: website

website:
  title: "Email for Data Science"
  site-url: https://posit-dev.github.io/email-for-data-science/
  navbar:
    left:
      - text: User Guide
        file: index.qmd
      - text: Reference
        file: reference/index.qmd
  sidebar:
    - title: User Guide
      contents:
        - index.qmd
        - summary.qmd
        - section: Content
          contents: 
            - content-embedding.qmd
            - content-layout.qmd
        - section: Configuring
          contents:
            - configuring-subject.qmd
            - configuring-attachments.qmd
        - section: Orchestrating
          contents:
            - orchestrating-auth.qmd
            - orchestrating-tests.qmd

quartodoc:
  package: emailer-lib
  dir: reference
  title: API Reference
  css: reference/_styles-quartodoc.css
  renderer:
    style: markdown
    table_style: description-list

  sections:
    - title: Section 1
      desc: >
        A test section
      contents:
        - send_quarto_email_with_gmail


format:
  html:
    theme:
      - cosmo
      - brand


