# The whole game

<!-- 
* Preview of nice email result
* Connecting to gmail
* Writing the email content
* Sending the email
* Content: Sending a fancier email
* Configuring: subject and attachments
* Orchestration: testing email 
-->



In this tutorial, we are going to send an email from a Gmail account. To do so, you will need to [create an App Password](https://support.google.com/accounts/answer/185833). Note this is only possible if you've [enabled 2-step verification](https://support.google.com/accounts/answer/185839).

<!--
I'm hestitant to directly put links like this: https://myaccount.google.com/apppasswords
Because it will instantly prompt the user to login to their gmail account, which might feel sketchy on a webpage from an unknown url.
-->

::: {.callout-tip}
This is just one of many options: it is also possible to send emails in Python from other email providers (Outlook, ProtonMail, etc.), or even from a custom domain. To skip ahead to a discussion of alternative sending methods, see [Authentication](orchestrating-auth.qmd)
:::

Once you've created your App Password, that is used as your Gmail password for sending with Python. 

There are many ways to store the password seperate from your email-sending code, so as to not expose any sensitive information. One such appraoch uses a `.env` file, and the ``dotenv` and `os` packages.

```{.sh filename=".env"}
GMAIL_APP_PASSWORD=abcd abcd abcd abcd
```

```{.python filename="main.py"}
import os
from dotenv import load_dotenv

load_dotenv()

your_gmail_address = "YourGmail@gmail.com"
gmail_app_password = os.environ["GMAIL_APP_PASSWORD"]
```

Check out the email content we will send.

<!-- {{< embed email-examples/summary-example.qmd#abc >}} -->

And now we send the email!

```{python}
# | eval: false
import redmail

redmail.gmail.username = your_gmail_address
redmail.gmail.password = gmail_app_password

redmail.gmail.send(
    subject="An Example Email",
    receivers=[username],
    html=email_html,
    text=email_plaintext,
)
```

<!-- 
Explain why email_plaintext is there?
-->

{{< embed email-examples/summary-example.qmd#email-output >}}
