# API Reference {.doc .doc-index}

## The Email Object

An email object that in a serializable, previewable format, optimized for emails with content generated by data scientists.


| | |
| --- | --- |
| [IntermediateEmail](IntermediateEmail.qmd#emailer_lib.IntermediateEmail) | A serializable, previewable, sendable email object for data science workflows. |
| [IntermediateEmail.write_preview_email](IntermediateEmail.write_preview_email.qmd#emailer_lib.IntermediateEmail.write_preview_email) | Write a preview HTML file with inline attachments embedded. |
| [IntermediateEmail.write_email_message](IntermediateEmail.write_email_message.qmd#emailer_lib.IntermediateEmail.write_email_message) | Convert the IntermediateEmail to a Python EmailMessage. |
| [IntermediateEmail.preview_send_email](IntermediateEmail.preview_send_email.qmd#emailer_lib.IntermediateEmail.preview_send_email) | Send a preview of the email to a test recipient. |

## Uploading emails

Converting emails to IntermediateEmails, at which point they can be previewed, tested, and sent.


| | |
| --- | --- |
| [quarto_json_to_intermediate_email](quarto_json_to_intermediate_email.qmd#emailer_lib.quarto_json_to_intermediate_email) | Convert a Quarto output metadata JSON file to an IntermediateEmail |
| [mjml_to_intermediate_email](mjml_to_intermediate_email.qmd#emailer_lib.mjml_to_intermediate_email) | Convert MJML markup to an IntermediateEmail |
| [redmail_to_intermediate_email](redmail_to_intermediate_email.qmd#emailer_lib.redmail_to_intermediate_email) | Convert a Redmail EmailMessage object to an IntermediateEmail |
| [yagmail_to_intermediate_email](yagmail_to_intermediate_email.qmd#emailer_lib.yagmail_to_intermediate_email) | Convert a Yagmail email object to an IntermediateEmail |

## Sending

Functions to sending emails with different providers. And a special handy one to bypass the intermediate object if you are sending a quarto email.


| | |
| --- | --- |
| [send_intermediate_email_with_gmail](send_intermediate_email_with_gmail.qmd#emailer_lib.send_intermediate_email_with_gmail) | Send an Intermediate Email object via Gmail. |
| [send_intermediate_email_with_smtp](send_intermediate_email_with_smtp.qmd#emailer_lib.send_intermediate_email_with_smtp) | Send an Intermediate Email object via SMTP. |
| [send_intermediate_email_with_redmail](send_intermediate_email_with_redmail.qmd#emailer_lib.send_intermediate_email_with_redmail) | Send an Intermediate Email object via Redmail. |
| [send_intermediate_email_with_yagmail](send_intermediate_email_with_yagmail.qmd#emailer_lib.send_intermediate_email_with_yagmail) | Send an Intermediate Email object via Yagmail. |
| [send_intermediate_email_with_mailgun](send_intermediate_email_with_mailgun.qmd#emailer_lib.send_intermediate_email_with_mailgun) | Send an Intermediate Email object via Mailgun. |
| [send_quarto_email_with_gmail](send_quarto_email_with_gmail.qmd#emailer_lib.send_quarto_email_with_gmail) | Send an email using Gmail with content from a Quarto metadata JSON file. |

## Utilities

Previews and more 


| | |
| --- | --- |
| [write_email_message_to_file](write_email_message_to_file.qmd#emailer_lib.write_email_message_to_file) | Writes the HTML content of an email message to a file, inlining any images referenced by Content-ID (cid). |